"""initial tables

Revision ID: 797db5cc443a
Revises: 
Create Date: 2026-09-16 14:10:55.466543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797db5cc443a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=128), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('cards',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('reading', sa.String(length=128), nullable=False),
    sa.Column('is_common', sa.BigInteger(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('jlpt', sa.Text(), nullable=False),
    sa.Column('senses', sa.Text(), nullable=False),
    sa.Column('localized_definition', sa.Text(), nullable=False),
    sa.Column('gloss_lang', sa.String(length=16), nullable=False),
    sa.Column('is_favorite', sa.BigInteger(), nullable=False),
    sa.Column('srs_data', sa.Text(), nullable=True),
    sa.Column('added_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deck', sa.String(length=64), nullable=False),
    sa.Column('ai_tutor_comment', sa.Text(), nullable=True),
    sa.Column('ai_memory_tip', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.create_index(op.f('ix_cards_updated_at'), 'cards', ['updated_at'], unique=False)
    op.create_table('review_logs',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('card_id', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_at', sa.BigInteger(), nullable=False),
    sa.Column('prev_interval_ms', sa.BigInteger(), nullable=False),
    sa.Column('new_interval_ms', sa.BigInteger(), nullable=False),
    sa.Column('prev_ease', sa.Float(), nullable=False),
    sa.Column('new_ease', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.create_index(op.f('ix_review_logs_reviewed_at'), 'review_logs', ['reviewed_at'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('llm_api_key', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('llm_custom_prompt', sa.Text(), nullable=False),
    sa.Column('llm_enabled', sa.BigInteger(), nullable=False),
    sa.Column('llm_gen_ui_enabled', sa.BigInteger(), nullable=False),
    sa.Column('source_language', sa.String(length=64), nullable=False),
    sa.Column('target_language', sa.String(length=64), nullable=False),
    sa.Column('has_completed_language_setup', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('word_views',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('first_viewed_at', sa.BigInteger(), nullable=False),
    sa.Column('last_viewed_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_views')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_review_logs_reviewed_at'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_cards_updated_at'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('users')
    # ### end Alembic commands ###
